Enable multiple tourguides
aegis-health-app/aegis-health-app-frontend pull request #29
Opened 2022-03-27 13:47 UTC by pointmekin

# Note (Please read)
- Due to the limitation of the `rn-tourguide` library, there could only be 1 tourguide inside the application. 
- This doesn't allow us to follow the design. 
- I found. a fork of this repository that enables the project to contain multiple tourguides. This is the link to that repository: https://github.com/b-steel/rn-tourguide/tree/multiple-tours
- I then create a new folder inside the src folder called "library" this will contain any external libraries that we want to hijack and include it in our project in the future. For compatibility and efficiency reasons, eslint rules will be disabled for this folder. 
- I have copied the content in the src folder of this forked repository and include it in `src/library/rn-multiple-tourguide` folder of our project.

Please check it out, or try running this in your emulator to ensure that everything's working fine. The expected result is that the tourguide on the home page and the settings page should follow their respective designs in figma. And it should not show any steps that doesn't exist in its own page.

2022-03-27 13:54 UTC, chuwong35122 commented
Could you post the screen recording for the change? And discuss more on 1 tour guide instance in the application for the team too?

2022-03-27 14:01 UTC, pointmekin commented
> Could you post the screen recording for the change? And discuss more on 1 tour guide instance in the application for the team too?

Updated PR notes

2022-03-27 19:00 UTC, pointmekin commented
Updated for the Elderly and Caretaker home screens.

2022-03-28 02:49 UTC, bweam requested changes

2022-03-28 02:49 UTC, bweam commented on src/config/axiosConfig.ts
> +        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUxLCJyb2xlIjoiQ2FyZXRha2VyIiwiaWF0IjoxNjQ4MzcwODU2LCJleHAiOjE2NDg5NzU2NTZ9.g730zlMLsPh-bAK7OrDIlJ-8ozMRAXJ1jSWRNuL1MGk';
Please remove JWT

2022-03-28 03:32 UTC, pointmekin commented on src/config/axiosConfig.ts
> +        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUxLCJyb2xlIjoiQ2FyZXRha2VyIiwiaWF0IjoxNjQ4MzcwODU2LCJleHAiOjE2NDg5NzU2NTZ9.g730zlMLsPh-bAK7OrDIlJ-8ozMRAXJ1jSWRNuL1MGk';
removed

2022-03-28 03:33 UTC, bweam approved these changes
LGTM

2022-03-28 04:08 UTC, merged

2022-05-03 14:18 UTC, ImFelippe365 commented
can you show us how to use the connected steps? i have the same problem, but idk use this library